services:
  op-geth:
    image: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:v1.101500.1
    restart: unless-stopped
    stop_grace_period: 5m
    entrypoint: /scripts/start-op-geth.sh
    volumes:
      - ./scripts/:/scripts
      - /home/ubuntu/op-data:/home/ubuntu/op-data
    ports:
      - 9993:8555
      - 9994:8556
      - 39393:39393/udp
      - 39393:39393/tcp

  op-node:
    image: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-node:v1.11.2
    restart: unless-stopped
    stop_grace_period: 5m
    entrypoint: /scripts/start-op-node.sh
    volumes:
      - ./scripts/:/scripts
      - /home/ubuntu/op-data:/home/ubuntu/op-data
    ports:
      - 9003:9003/udp
      - 9003:9003/tcp
      - 9545:9545


  geth:
    image: ethereum/client-go:v1.15.2
    restart: unless-stopped
    stop_grace_period: 5m
    entrypoint: /scripts/start-geth.sh
    volumes:
      - ./scripts/:/scripts
      - /home/ubuntu/data:/home/ubuntu/data
    ports:
      - 8545:8545
      - 8546:8546
      - 30303:30303
      - 30303:30303


  prysm:
    image: gcr.io/prysmaticlabs/prysm/beacon-chain:v5.3.0
    container_name: prysm-beacon
    restart: unless-stopped
    ports:
      - "4000:4000"     
      - "3500:3500"     
      - "8080:8080"    
    volumes:
      - /home/ubuntu/data:/home/ubuntu/data
    command:
      - "--checkpoint-sync-url=https://beaconstate.info"
      - "--genesis-beacon-api-url=https://beaconstate.info"
      - "--datadir=/home/ubuntu/data/prysm-data"
      - "--jwt-secret=/home/ubuntu/data/secret.jwt"
      - "--execution-endpoint=http://geth:8551"
      - "--rpc-host=0.0.0.0"
      - "--grpc-gateway-host=0.0.0.0"
      - "--monitoring-host=0.0.0.0"
      - "--accept-terms-of-use"

